# 로컬 도커
version: "3.9"

services:
  app:
    image: python:3.11
    container_name: alive-v-api-dev
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env.dev
    command: >
      sh -c "
      pip install poetry &&
      poetry install &&
      poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    container_name: alive-v-db
    restart: always
    environment:
      POSTGRES_USER: alive_v_user
      POSTGRES_PASSWORD: alive_v_password
      POSTGRES_DB: alive_v_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data_dev:
