version: "3.9"

services:
  app:
    image: python:3.11
    container_name: alive-v-api-prod
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env.prod
    command: >
      sh -c "
      pip install poetry &&
      poetry install &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"

volumes:
  postgres_data_prod:
